#! /usr/bin/python
import os;

here = os.path.abspath( "./" );
cxxflags = "-fpermissive -g -Wpointer-arith -pedantic -O2 -W -Wall -Wno-variadic-macros";
libs = [ "g2", "pthread", ];
libpath = [ os.path.join( here, "../../../g2/build/" ) ];
includepath= [ os.path.join( here, "../../../g2/src/" ) ];
files = [
	  "main.cpp",
	  "dispatchworker.cpp",
	  "handlerbase.cpp",
];

env = Environment( CXXFLAGS = cxxflags,
	  			   CPPPATH = includepath,
	  			   LIBS = libs,
				   LIBPATH = libpath );

env.Program( "a.out", files );
