#! /usr/bin/python
# -*- coding:utf-8 -*-

import os;
Import( "LIBPATH" );
Import( "LIBS" );
Import( "build_mock" );

libs = ["dispatcher"] + LIBS[:];
libpath = ["../../build/parallel/"] + LIBPATH[:];

build_mock( libpath, libs );
