#! /usr/bin/python
# -*- coding:utf-8 -*-

import os;

compileFlags = [
	"-fpermissive",
	"-g",
	"-Wpointer-arith",
	"-W",
	"-Wall",
	"-Wno-variadic-macros",
	"-pedantic",
	"-O2",
	"-I/home/kj/dev/g2/src/",
	];

sconscripts = [
	"dispatch_models/parallel/SConscript",
	];

env = Environment( CXXFLAGS = compileFlags );
Export( "env" );

def Main():
	SConscript( sconscripts );
	
	for i in os.listdir( "./" ):
		if i.endswith( ".cpp" ) == False:
			continue;
		env.Object( i );


Main();
# EOF
